// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Cart
{
    public int CartId { get; set; }

    public int UserId { get; set; }

    public int ProductSpecificationId { get; set; }

    public int Quantity { get; set; }

    public virtual ProductSpecification ProductSpecification { get; set; }

    public virtual User User { get; set; }
}