// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ChatMessage
{
    public int ChatMessageId { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public string Content { get; set; }

    public DateTimeOffset SentAt { get; set; }

    public bool IsRead { get; set; }

    public string ImagePath { get; set; }

    public virtual ICollection<ChatMessageImage> ChatMessageImage { get; set; } = new List<ChatMessageImage>();

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}