// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ChatMessageImage
{
    public int ChatMessageImageId { get; set; }

    public int ChatMessageId { get; set; }

    public string ImagePath { get; set; }

    public int SortOrder { get; set; }

    public virtual ChatMessage ChatMessage { get; set; }
}