// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CLOthings_API.Models;

public partial class CLOthingsContext : DbContext
{
    public CLOthingsContext(DbContextOptions<CLOthingsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Cart { get; set; }

    public virtual DbSet<ChatMessage> ChatMessage { get; set; }

    public virtual DbSet<ChatMessageImage> ChatMessageImage { get; set; }

    public virtual DbSet<CommunityFavorite> CommunityFavorite { get; set; }

    public virtual DbSet<CommunityPost> CommunityPost { get; set; }

    public virtual DbSet<Coupon> Coupon { get; set; }

    public virtual DbSet<CustomerFavorite> CustomerFavorite { get; set; }

    public virtual DbSet<CustomerService> CustomerService { get; set; }

    public virtual DbSet<GroupCart> GroupCart { get; set; }

    public virtual DbSet<GroupCustomerFavorite> GroupCustomerFavorite { get; set; }

    public virtual DbSet<GroupCustomerService> GroupCustomerService { get; set; }

    public virtual DbSet<GroupDiscountStandard> GroupDiscountStandard { get; set; }

    public virtual DbSet<GroupOrder> GroupOrder { get; set; }

    public virtual DbSet<GroupOrderDetail> GroupOrderDetail { get; set; }

    public virtual DbSet<GroupPaymentMethod> GroupPaymentMethod { get; set; }

    public virtual DbSet<GroupProduct> GroupProduct { get; set; }

    public virtual DbSet<GroupProductCategory> GroupProductCategory { get; set; }

    public virtual DbSet<GroupProductSpecification> GroupProductSpecification { get; set; }

    public virtual DbSet<GroupSellerStatistic> GroupSellerStatistic { get; set; }

    public virtual DbSet<GroupShipper> GroupShipper { get; set; }

    public virtual DbSet<GroupSupplier> GroupSupplier { get; set; }

    public virtual DbSet<Invoice> Invoice { get; set; }

    public virtual DbSet<Notification> Notification { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<OrderDetail> OrderDetail { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }

    public virtual DbSet<PostComment> PostComment { get; set; }

    public virtual DbSet<PostImage> PostImage { get; set; }

    public virtual DbSet<PostLike> PostLike { get; set; }

    public virtual DbSet<PostShortUrl> PostShortUrl { get; set; }

    public virtual DbSet<PostReport> PostReport { get; set; }

    public virtual DbSet<PostTaggedProduct> PostTaggedProduct { get; set; }

    public virtual DbSet<Product> Product { get; set; }

    public virtual DbSet<ProductCategory> ProductCategory { get; set; }

    public virtual DbSet<ProductImg> ProductImg { get; set; }

    public virtual DbSet<ProductReturn> ProductReturn { get; set; }

    public virtual DbSet<ProductReturnDetail> ProductReturnDetail { get; set; }

    public virtual DbSet<ProductSpecification> ProductSpecification { get; set; }

    public virtual DbSet<Review> Review { get; set; }

    public virtual DbSet<SellerStatistic> SellerStatistic { get; set; }

    public virtual DbSet<Shipper> Shipper { get; set; }

    public virtual DbSet<Supplier> Supplier { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserAddress> UserAddress { get; set; }

    public virtual DbSet<UserFollow> UserFollow { get; set; }

    public virtual DbSet<UserOAuth> UserOAuth { get; set; }

    public virtual DbSet<UserPasswordResetToken> UserPasswordResetToken { get; set; }

    public virtual DbSet<UserProfile> UserProfile { get; set; }

    public virtual DbSet<UserRefreshToken> UserRefreshToken { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasOne(d => d.ProductSpecification).WithMany(p => p.Cart)
                .HasForeignKey(d => d.ProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cart_Spec");

            entity.HasOne(d => d.User).WithMany(p => p.Cart)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Cart_User");
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.ChatMessageId).HasName("PK__ChatMess__9AB61035599F12DE");

            entity.HasIndex(e => new { e.ReceiverId, e.SenderId }, "IX_ChatMessage_ReceiverId_SenderId");

            entity.HasIndex(e => new { e.SenderId, e.ReceiverId }, "IX_ChatMessage_SenderId_ReceiverId");

            entity.Property(e => e.Content).HasMaxLength(1000);
            entity.Property(e => e.ImagePath).HasMaxLength(255);
            entity.Property(e => e.SentAt).HasDefaultValueSql("(sysdatetimeoffset())");

            entity.HasOne(d => d.Receiver).WithMany(p => p.ChatMessageReceiver)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatMessage_Receiver");

            entity.HasOne(d => d.Sender).WithMany(p => p.ChatMessageSender)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatMessage_Sender");
        });

        modelBuilder.Entity<ChatMessageImage>(entity =>
        {
            entity.HasKey(e => e.ChatMessageImageId).HasName("PK__ChatMess__4147580536758337");

            entity.HasIndex(e => e.ChatMessageId, "IX_ChatMessageImage_ChatMessageId");

            entity.Property(e => e.ImagePath)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.ChatMessage).WithMany(p => p.ChatMessageImage)
                .HasForeignKey(d => d.ChatMessageId)
                .HasConstraintName("FK_ChatMessageImage_ChatMessage");
        });

        modelBuilder.Entity<CommunityFavorite>(entity =>
        {
            entity.HasKey(e => e.CommunityFavoriteId).HasName("PK_dbo.CommunityFavorite");

            entity.HasOne(d => d.User).WithMany(p => p.CommunityFavorite)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.CommunityFavorite_User");
        });

        modelBuilder.Entity<CommunityPost>(entity =>
        {
            entity.Property(e => e.PostDate).HasDefaultValueSql("(getdate())", "DF_CommunityPost_PostDate");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.CommunityPost)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CommunityPost_User");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.Property(e => e.CouponCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DiscountType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.DiscountValue)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.MinPrice).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<CustomerFavorite>(entity =>
        {
            entity.HasIndex(e => new { e.UserId, e.ProductId }, "UQ_Favorites").IsUnique();

            entity.HasOne(d => d.Product).WithMany(p => p.CustomerFavorite)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CustomerFavorite_Product");

            entity.HasOne(d => d.User).WithMany(p => p.CustomerFavorite)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CustomerFavorite_User");
        });

        modelBuilder.Entity<CustomerService>(entity =>
        {
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Order).WithMany(p => p.CustomerService)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_CustomerService_Order");
        });

        modelBuilder.Entity<GroupCart>(entity =>
        {
            entity.Property(e => e.AddDate).HasDefaultValueSql("(getdate())", "DF_GroupCart_AddDate");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupCart)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCart_Product");

            entity.HasOne(d => d.GroupProductSpecification).WithMany(p => p.GroupCart)
                .HasForeignKey(d => d.GroupProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCart_Spec");

            entity.HasOne(d => d.User).WithMany(p => p.GroupCart)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserId");
        });

        modelBuilder.Entity<GroupCustomerFavorite>(entity =>
        {
            entity.HasIndex(e => new { e.UserId, e.GroupProductId }, "UQ_GroupFavorites").IsUnique();

            entity.Property(e => e.AddDate).HasDefaultValueSql("(getdate())", "DF_GroupCustomerFavorite_AddDate");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupCustomerFavorite)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupCustomerFavorite_Product");

            entity.HasOne(d => d.User).WithMany(p => p.GroupCustomerFavorite)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_GroupCustomerFavorite_User");
        });

        modelBuilder.Entity<GroupCustomerService>(entity =>
        {
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.GroupOrder).WithMany(p => p.GroupCustomerService)
                .HasForeignKey(d => d.GroupOrderId)
                .HasConstraintName("FK_GroupCustomerService_Order");
        });

        modelBuilder.Entity<GroupDiscountStandard>(entity =>
        {
            entity.Property(e => e.DiscountRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.ThresholdAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ThresholdCount)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TierLevel).HasMaxLength(50);

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupDiscountStandard)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupDiscountStandard_Product");
        });

        modelBuilder.Entity<GroupOrder>(entity =>
        {
            entity.Property(e => e.Freight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())", "DF_GroupOrder_OrderDate");
            entity.Property(e => e.PickupMethod)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ShipAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ShipName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipPhone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.GroupShipper).WithMany(p => p.GroupOrder)
                .HasForeignKey(d => d.GroupShipperId)
                .HasConstraintName("FK_GroupOrder_Shipper");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.GroupOrder)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrder_Payment");

            entity.HasOne(d => d.User).WithMany(p => p.GroupOrder)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrder_User");
        });

        modelBuilder.Entity<GroupOrderDetail>(entity =>
        {
            entity.Property(e => e.Discount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.GroupOrder).WithMany(p => p.GroupOrderDetail)
                .HasForeignKey(d => d.GroupOrderId)
                .HasConstraintName("FK_GroupOrderDetail_Order");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupOrderDetail)
                .HasForeignKey(d => d.GroupProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrderDetail_Product");

            entity.HasOne(d => d.GroupProductSpecification).WithMany(p => p.GroupOrderDetail)
                .HasForeignKey(d => d.GroupProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupOrderDetail_Spec");
        });

        modelBuilder.Entity<GroupPaymentMethod>(entity =>
        {
            entity.Property(e => e.CardBrand)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ExpireAt)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.GroupPaymentMethod)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_GroupPaymentMethod_User");
        });

        modelBuilder.Entity<GroupProduct>(entity =>
        {
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductImg).HasMaxLength(500);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.GroupProductCategory).WithMany(p => p.GroupProduct)
                .HasForeignKey(d => d.GroupProductCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupProduct_Category");

            entity.HasOne(d => d.GroupSupplier).WithMany(p => p.GroupProduct)
                .HasForeignKey(d => d.GroupSupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupProduct_Supplier");
        });

        modelBuilder.Entity<GroupProductCategory>(entity =>
        {
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<GroupProductSpecification>(entity =>
        {
            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupProductSpecification)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupProductSpecification_Product");
        });

        modelBuilder.Entity<GroupSellerStatistic>(entity =>
        {
            entity.HasKey(e => e.GroupSellerStatisticsId);

            entity.Property(e => e.AddCartCount).HasDefaultValue(0, "DF_GroupSellerStatistic_AddCartCount");
            entity.Property(e => e.CheckoutCount).HasDefaultValue(0, "DF_GroupSellerStatistic_CheckoutCount");
            entity.Property(e => e.FavorCount).HasDefaultValue(0, "DF_GroupSellerStatistic_FavorCount");
            entity.Property(e => e.StatisticDate).HasDefaultValueSql("(getdate())", "DF_GroupSellerStatistic_StatisticDate");
            entity.Property(e => e.ViewCount).HasDefaultValue(0, "DF_GroupSellerStatistic_ViewCount");

            entity.HasOne(d => d.GroupProduct).WithMany(p => p.GroupSellerStatistic)
                .HasForeignKey(d => d.GroupProductId)
                .HasConstraintName("FK_GroupSellerStatistic_Product");

            entity.HasOne(d => d.GroupSupplier).WithMany(p => p.GroupSellerStatistic)
                .HasForeignKey(d => d.GroupSupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupSellerStatistic_Supplier");
        });

        modelBuilder.Entity<GroupShipper>(entity =>
        {
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipperName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<GroupSupplier>(entity =>
        {
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.ContactName).HasMaxLength(100);
            entity.Property(e => e.ContactTitle).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.Property(e => e.CarrierCode).HasMaxLength(50);
            entity.Property(e => e.CompanyName).HasMaxLength(100);
            entity.Property(e => e.DonationCode).HasMaxLength(50);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.InvoiceDate).HasDefaultValueSql("(getdate())", "DF_Invoice_InvoiceDate");
            entity.Property(e => e.InvoiceType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RandomCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TaxCode).HasMaxLength(50);
            entity.Property(e => e.TotalPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Order).WithMany(p => p.Invoice)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_Invoice_Order");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId);

            entity.Property(e => e.Type).HasMaxLength(20).IsRequired();
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetimeoffset())");
            entity.Property(e => e.IsRead).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_User");

            entity.HasOne(d => d.FromUser).WithMany()
                .HasForeignKey(d => d.FromUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_FromUser");

            entity.HasOne(d => d.CommunityPost).WithMany()
                .HasForeignKey(d => d.CommunityPostId)
                .IsRequired(false)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_CommunityPost");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.Freight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())", "DF_Order_OrderDate");
            entity.Property(e => e.ShipAddress)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ShipName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipPhone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Coupon).WithMany(p => p.Order)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK_Order_Coupon");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Order)
                .HasForeignKey(d => d.PaymentMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Payment");

            entity.HasOne(d => d.Shipper).WithMany(p => p.Order)
                .HasForeignKey(d => d.ShipperId)
                .HasConstraintName("FK_Order_Shipper");

            entity.HasOne(d => d.User).WithMany(p => p.Order)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_User");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.Property(e => e.Discount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Coupon).WithMany(p => p.OrderDetail)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK_OrderDetail_Coupon");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetail)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderDetail_Order");

            entity.HasOne(d => d.ProductSpecification).WithMany(p => p.OrderDetail)
                .HasForeignKey(d => d.ProductSpecificationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetail_Spec");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.Property(e => e.CardBrand)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ExpireAt)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.PaymentMethod)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_PaymentMethod_User");
        });

        modelBuilder.Entity<PostComment>(entity =>
        {
            entity.Property(e => e.CommentDate).HasDefaultValueSql("(getdate())", "DF_PostComment_CommentDate");
            entity.Property(e => e.CommentText).IsRequired();

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostComment)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostComment_Post");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .HasConstraintName("FK_PostComment_Parent");

            entity.HasOne(d => d.User).WithMany(p => p.PostComment)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostComment_User");
        });

        modelBuilder.Entity<PostImage>(entity =>
        {
            entity.Property(e => e.ImageFileName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.SortOrder).HasDefaultValue(1, "DF_PostImage_SortOrder");

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostImage)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostImage_Post");
        });

        modelBuilder.Entity<PostLike>(entity =>
        {
            entity.HasKey(e => e.PostLikesId);

            entity.HasIndex(e => new { e.CommunityPostId, e.UserId }, "UQ_PostLikes").IsUnique();

            entity.Property(e => e.LikeDate).HasDefaultValueSql("(getdate())", "DF_PostLike_LikeDate");

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostLike)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostLike_Post");

            entity.HasOne(d => d.User).WithMany(p => p.PostLike)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostLike_User");
        });

        modelBuilder.Entity<PostShortUrl>(entity =>
        {
            entity.HasKey(e => e.PostShortUrlId).HasName("PK__PostShor__EBFDF692E99A53FC");

            entity.HasIndex(e => e.CommunityPostId, "UQ_PostShortUrl_CommunityPostId").IsUnique();

            entity.HasIndex(e => e.ShortCode, "UQ_PostShortUrl_ShortCode").IsUnique();

            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetimeoffset())");
            entity.Property(e => e.ShortCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.HasOne(d => d.CommunityPost).WithOne(p => p.PostShortUrl)
                .HasForeignKey<PostShortUrl>(d => d.CommunityPostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostShortUrl_CommunityPost");
        });

        modelBuilder.Entity<PostReport>(entity =>
        {
            entity.HasKey(e => e.PostReportId);

            entity.HasIndex(e => new { e.CommunityPostId, e.ReporterId }, "UQ_PostReport_Post_Reporter").IsUnique();

            entity.Property(e => e.Reason).HasMaxLength(200).IsRequired();
            entity.Property(e => e.CreatedDate).HasDefaultValueSql("(sysdatetimeoffset())");

            entity.HasOne(d => d.CommunityPost).WithMany()
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostReport_CommunityPost");

            entity.HasOne(d => d.Reporter).WithMany()
                .HasForeignKey(d => d.ReporterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostReport_Reporter");
        });


        modelBuilder.Entity<PostTaggedProduct>(entity =>
        {
            entity.Property(e => e.ProductRoute).HasMaxLength(255);

            entity.HasOne(d => d.CommunityPost).WithMany(p => p.PostTaggedProduct)
                .HasForeignKey(d => d.CommunityPostId)
                .HasConstraintName("FK_PostTaggedProduct_Post");

            entity.HasOne(d => d.Product).WithMany(p => p.PostTaggedProduct)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostTaggedProduct_Product");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.ProductCategory).WithMany(p => p.Product)
                .HasForeignKey(d => d.ProductCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Category");

            entity.HasOne(d => d.Supplier).WithMany(p => p.Product)
                .HasForeignKey(d => d.SupplierId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Supplier");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ProductImg>(entity =>
        {
            entity.Property(e => e.ProductImgFile)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImg)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductImg_Product");
        });

        modelBuilder.Entity<ProductReturn>(entity =>
        {
            entity.HasKey(e => e.ReturnId).HasName("PK__Return__F445E9A8FA07816E");

            entity.Property(e => e.Reason).HasMaxLength(500);
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Order).WithMany(p => p.ProductReturn)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Order");

            entity.HasOne(d => d.User).WithMany(p => p.ProductReturn)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_User");
        });

        modelBuilder.Entity<ProductReturnDetail>(entity =>
        {
            entity.HasKey(e => e.ReturnDetailId).HasName("PK__ReturnDe__8B89C98A68020433");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.ProductReturnDetail)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReturnDetail_OrderDetail");

            entity.HasOne(d => d.Return).WithMany(p => p.ProductReturnDetail)
                .HasForeignKey(d => d.ReturnId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ReturnDetail_Return");
        });

        modelBuilder.Entity<ProductSpecification>(entity =>
        {
            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Size)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductSpecification)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductSpecification_Product");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.Property(e => e.ReviewDatetime).HasDefaultValueSql("(getdate())", "DF_Review_ReviewDatetime");
            entity.Property(e => e.ReviewImg).HasMaxLength(255);

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.Review)
                .HasForeignKey(d => d.OrderDetailId)
                .HasConstraintName("FK_Review_OrderDetail");

            entity.HasOne(d => d.User).WithMany(p => p.Review)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Review_User");
        });

        modelBuilder.Entity<SellerStatistic>(entity =>
        {
            entity.HasKey(e => e.SellerStatisticsId);

            entity.Property(e => e.AddCartCount).HasDefaultValue(0, "DF_SellerStatistic_AddCartCount");
            entity.Property(e => e.CheckoutCount).HasDefaultValue(0, "DF_SellerStatistic_CheckoutCount");
            entity.Property(e => e.FavorCount).HasDefaultValue(0, "DF_SellerStatistic_FavorCount");
            entity.Property(e => e.StatisticsDate).HasDefaultValueSql("(getdate())", "DF_SellerStatistic_StatisticsDate");
            entity.Property(e => e.ViewCount).HasDefaultValue(0, "DF_SellerStatistic_ViewCount");

            entity.HasOne(d => d.Product).WithMany(p => p.SellerStatistic)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_SellerStatistic_Product");
        });

        modelBuilder.Entity<Shipper>(entity =>
        {
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ShipperName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.ContactEmail).HasMaxLength(100);
            entity.Property(e => e.ContactName).HasMaxLength(100);
            entity.Property(e => e.ContactTitle).HasMaxLength(100);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Account)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CountryCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())", "DF_User_CreatedAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TwoFactorEnabled).HasDefaultValue(false, "DF_User_TwoFactorEnabled");
            entity.Property(e => e.TwoFactorSecret)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())", "DF_User_UpdatedAt");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<UserAddress>(entity =>
        {
            entity.Property(e => e.AddressDetail).HasMaxLength(255);
            entity.Property(e => e.IsDefault).HasDefaultValue(false, "DF_UserAddress_IsDefault");
            entity.Property(e => e.PostalCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RecipientName).HasMaxLength(100);
            entity.Property(e => e.RecipientPhone).HasMaxLength(50);

            entity.HasOne(d => d.User).WithMany(p => p.UserAddress)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserAddress_User");
        });

        modelBuilder.Entity<UserFollow>(entity =>
        {
            entity.HasIndex(e => new { e.FollowerId, e.FollowingId }, "UQ_UserFollows").IsUnique();

            entity.Property(e => e.FollowDate).HasDefaultValueSql("(getdate())", "DF_UserFollow_FollowDate");

            entity.HasOne(d => d.Follower).WithMany(p => p.UserFollowFollower)
                .HasForeignKey(d => d.FollowerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollow_Follower");

            entity.HasOne(d => d.Following).WithMany(p => p.UserFollowFollowing)
                .HasForeignKey(d => d.FollowingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFollow_Following");
        });

        modelBuilder.Entity<UserOAuth>(entity =>
        {
            entity.HasIndex(e => new { e.Provider, e.ProviderUserId }, "UQ_UserOAuth_Provider_ProviderUserId").IsUnique();

            entity.HasIndex(e => new { e.UserId, e.Provider }, "UQ_UserOAuth_UserId_Provider").IsUnique();

            entity.Property(e => e.AccessToken)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Provider)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ProviderUserId)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.RefreshToken)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())", "DF_UserOAuth_UpdatedAt");

            entity.HasOne(d => d.User).WithMany(p => p.UserOAuth)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserOAuth_User");
        });

        modelBuilder.Entity<UserPasswordResetToken>(entity =>
        {
            entity.HasKey(e => e.UserPasswordResetTokenId).HasName("PK__UserPass__2B5909C19F933AF3");

            entity.HasIndex(e => e.TokenHash, "IX_UserPasswordResetToken_TokenHash").IsUnique();

            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.UserPasswordResetToken)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserPasswordResetToken_User");
        });

        modelBuilder.Entity<UserProfile>(entity =>
        {
            entity.Property(e => e.Avatar).HasMaxLength(500);
            entity.Property(e => e.FirstName).HasMaxLength(50);
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Intro).HasMaxLength(500);
            entity.Property(e => e.LastName).HasMaxLength(50);
            entity.Property(e => e.StyleTag).HasMaxLength(100);

            entity.HasOne(d => d.User).WithMany(p => p.UserProfile)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserProfile_User");
        });

        modelBuilder.Entity<UserRefreshToken>(entity =>
        {
            entity.HasKey(e => e.UserRefreshTokenId).HasName("PK__UserRefr__76DBA1D1C64A0B50");

            entity.HasIndex(e => e.TokenHash, "IX_UserRefreshToken_TokenHash").IsUnique();

            entity.Property(e => e.ReplacedByTokenHash).HasMaxLength(200);
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.User).WithMany(p => p.UserRefreshToken)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRefreshToken_User");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}