// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class CommunityFavorite
{
    public int CommunityFavoriteId { get; set; }

    public int UserId { get; set; }

    public int CommunityPostId { get; set; }

    public virtual User User { get; set; }
}