// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class CommunityPost
{
    public int CommunityPostId { get; set; }

    public int UserId { get; set; }

    public string Content { get; set; }

    public DateTimeOffset PostDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<PostComment> PostComment { get; set; } = new List<PostComment>();

    public virtual ICollection<PostImage> PostImage { get; set; } = new List<PostImage>();

    public virtual ICollection<PostLike> PostLike { get; set; } = new List<PostLike>();

    public virtual PostShortUrl PostShortUrl { get; set; }

    public virtual ICollection<PostTaggedProduct> PostTaggedProduct { get; set; } = new List<PostTaggedProduct>();

    public virtual User User { get; set; }
}