// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Coupon
{
    public int CouponId { get; set; }

    public string CouponCode { get; set; }

    public string DiscountType { get; set; }

    public string DiscountValue { get; set; }

    public decimal MinPrice { get; set; }

    public DateTimeOffset? ValidStart { get; set; }

    public DateTimeOffset? ValidEnd { get; set; }

    public int? UsageLimit { get; set; }

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();
}