// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupOrderDetail
{
    public int GroupOrderDetailId { get; set; }

    public int GroupProductId { get; set; }

    public int GroupProductSpecificationId { get; set; }

    public int GroupOrderId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public virtual GroupOrder GroupOrder { get; set; }

    public virtual GroupProduct GroupProduct { get; set; }

    public virtual GroupProductSpecification GroupProductSpecification { get; set; }
}