// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupOrder
{
    public int GroupOrderId { get; set; }

    public int UserId { get; set; }

    public string Status { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTimeOffset OrderDate { get; set; }

    public DateTimeOffset? ShipperDate { get; set; }

    public int? GroupShipperId { get; set; }

    public string PickupMethod { get; set; }

    public string ShipName { get; set; }

    public string ShipAddress { get; set; }

    public string ShipPhone { get; set; }

    public decimal Freight { get; set; }

    public int PaymentMethodId { get; set; }

    public virtual ICollection<GroupCustomerService> GroupCustomerService { get; set; } = new List<GroupCustomerService>();

    public virtual ICollection<GroupOrderDetail> GroupOrderDetail { get; set; } = new List<GroupOrderDetail>();

    public virtual GroupShipper GroupShipper { get; set; }

    public virtual GroupPaymentMethod PaymentMethod { get; set; }

    public virtual User User { get; set; }
}