// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupDiscountStandard
{
    public int GroupDiscountStandardId { get; set; }

    public int GroupProductId { get; set; }

    public string TierLevel { get; set; }

    public string ThresholdCount { get; set; }

    public decimal? ThresholdAmount { get; set; }

    public decimal? DiscountRate { get; set; }

    public virtual GroupProduct GroupProduct { get; set; }
}