// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupShipper
{
    public int GroupShipperId { get; set; }

    public string ShipperName { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public virtual ICollection<GroupOrder> GroupOrder { get; set; } = new List<GroupOrder>();
}