// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupSupplier
{
    public int GroupSupplierId { get; set; }

    public string SupplierName { get; set; }

    public string ContactName { get; set; }

    public string ContactTitle { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<GroupProduct> GroupProduct { get; set; } = new List<GroupProduct>();

    public virtual ICollection<GroupSellerStatistic> GroupSellerStatistic { get; set; } = new List<GroupSellerStatistic>();
}