// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupProduct
{
    public int GroupProductId { get; set; }

    public string ProductName { get; set; }

    public int GroupSupplierId { get; set; }

    public int GroupProductCategoryId { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public DateTimeOffset? SalesStart { get; set; }

    public DateTimeOffset? SalesEnd { get; set; }

    public string ProductImg { get; set; }

    public virtual ICollection<GroupCart> GroupCart { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupCustomerFavorite> GroupCustomerFavorite { get; set; } = new List<GroupCustomerFavorite>();

    public virtual ICollection<GroupDiscountStandard> GroupDiscountStandard { get; set; } = new List<GroupDiscountStandard>();

    public virtual ICollection<GroupOrderDetail> GroupOrderDetail { get; set; } = new List<GroupOrderDetail>();

    public virtual GroupProductCategory GroupProductCategory { get; set; }

    public virtual ICollection<GroupProductSpecification> GroupProductSpecification { get; set; } = new List<GroupProductSpecification>();

    public virtual ICollection<GroupSellerStatistic> GroupSellerStatistic { get; set; } = new List<GroupSellerStatistic>();

    public virtual GroupSupplier GroupSupplier { get; set; }
}