// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupSellerStatistic
{
    public int GroupSellerStatisticsId { get; set; }

    public int GroupSupplierId { get; set; }

    public int GroupProductId { get; set; }

    public int? AddCartCount { get; set; }

    public int? CheckoutCount { get; set; }

    public int? ViewCount { get; set; }

    public int? FavorCount { get; set; }

    public DateTimeOffset? StatisticDate { get; set; }

    public virtual GroupProduct GroupProduct { get; set; }

    public virtual GroupSupplier GroupSupplier { get; set; }
}