// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupCustomerService
{
    public int GroupCustomerServiceId { get; set; }

    public int GroupOrderId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Content { get; set; }

    public string Title { get; set; }

    // 管理端回覆的內容，還沒回覆的話是 null
    public string ReplyContent { get; set; }

    // 回覆的時間，還沒回覆的話是 null
    public DateTimeOffset? RepliedAt { get; set; }

    public virtual GroupOrder GroupOrder { get; set; }
}