// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class GroupCart
{
    public int GroupCartId { get; set; }

    public int UserId { get; set; }

    public int GroupProductId { get; set; }

    public int GroupProductSpecificationId { get; set; }

    public int Quantity { get; set; }

    public DateTimeOffset AddDate { get; set; }

    public virtual GroupProduct GroupProduct { get; set; }

    public virtual GroupProductSpecification GroupProductSpecification { get; set; }

    public virtual User User { get; set; }
}