// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public int OrderId { get; set; }

    public string InvoiceType { get; set; }

    public string RandomCode { get; set; }

    public DateTimeOffset InvoiceDate { get; set; }

    public decimal TotalPrice { get; set; }

    public string Email { get; set; }

    public string CarrierCode { get; set; }

    public string TaxCode { get; set; }

    public string CompanyName { get; set; }

    public string DonationCode { get; set; }

    public virtual Order Order { get; set; }
}