// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int UserId { get; set; }

    public int FromUserId { get; set; }

    public string Type { get; set; }

    public int? CommunityPostId { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public bool IsRead { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }

    public virtual User FromUser { get; set; }

    public virtual User User { get; set; }
}