// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int ProductSpecificationId { get; set; }

    public int OrderId { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public decimal? Discount { get; set; }

    public int? CouponId { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Order Order { get; set; }

    public virtual ProductSpecification ProductSpecification { get; set; }

    public virtual ICollection<Review> Review { get; set; } = new List<Review>();
}