// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public string Status { get; set; }

    public DateTimeOffset OrderDate { get; set; }

    public DateTimeOffset? ShippedDate { get; set; }

    public int? ShipperId { get; set; }

    public string ShipName { get; set; }

    public string ShipAddress { get; set; }

    public string ShipPhone { get; set; }

    public decimal Freight { get; set; }

    public int? InvoiceId { get; set; }

    public int PaymentMethodId { get; set; }

    public int? CouponId { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual ICollection<CustomerService> CustomerService { get; set; } = new List<CustomerService>();

    public virtual ICollection<Invoice> Invoice { get; set; } = new List<Invoice>();

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual Shipper Shipper { get; set; }

    public virtual User User { get; set; }
}