// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PaymentMethod
{
    public int PaymentMethodId { get; set; }

    public int UserId { get; set; }

    public string Provider { get; set; }

    public string Token { get; set; }

    public string CardBrand { get; set; }

    public string ExpireAt { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}