// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PostImage
{
    public int PostImageId { get; set; }

    public int CommunityPostId { get; set; }

    public string ImageFileName { get; set; }

    public int SortOrder { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }
}