// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PostTaggedProduct
{
    public int PostTaggedProductId { get; set; }

    public int CommunityPostId { get; set; }

    public int ProductId { get; set; }

    public string ProductRoute { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }

    public virtual Product Product { get; set; }
}