// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PostReport
{
    public int PostReportId { get; set; }

    public int CommunityPostId { get; set; }

    public int ReporterId { get; set; }

    public string Reason { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }

    public virtual User Reporter { get; set; }
}