// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PostShortUrl
{
    public int PostShortUrlId { get; set; }

    public int CommunityPostId { get; set; }

    public string ShortCode { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }
}