// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class PostComment
{
    public int PostCommentId { get; set; }

    public int? ParentCommentId { get; set; }

    public int CommunityPostId { get; set; }

    public int UserId { get; set; }

    public string CommentText { get; set; }

    public DateTimeOffset CommentDate { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }

    public virtual ICollection<PostComment> InverseParentComment { get; set; } = new List<PostComment>();

    public virtual PostComment ParentComment { get; set; }

    public virtual User User { get; set; }
}