// 這個檔案是照專案原本用 EF Core Power Tools 對資料庫做 Scaffold 產生 Model 的風格手動寫的
// （其他 Models 資料夾底下的檔案最上面都有 <auto-generated> 標記，是因為它們是拿現有資料庫
// 表格「反向產生」出來的，不是手動寫的）。
// 之後如果照 create_PostShortUrl_table.sql 把資料表建到資料庫之後，再重新對資料庫做一次
// Scaffold，工具會自動長出一份跟這個檔案幾乎一樣的版本，屆時直接用工具產生的版本蓋掉這個
// 手動版就可以了，不用特別保留這一份。
#nullable disable
using System;

namespace CLOthings_API.Models;

public partial class PostShortUrl
{
    public int PostShortUrlId { get; set; }

    public int CommunityPostId { get; set; }

    public string ShortCode { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public virtual CommunityPost CommunityPost { get; set; }
}