// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ProductSpecification
{
    public int ProductSpecificationId { get; set; }

    public int ProductId { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public int Inventory { get; set; }

    public int? UnitOnOrder { get; set; }

    public int ReorderLevel { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual ICollection<OrderDetail> OrderDetail { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }
}