// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int SupplierId { get; set; }

    public int ProductCategoryId { get; set; }

    public string Description { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public DateTimeOffset? SalesStartDate { get; set; }

    public DateTimeOffset? SalesEndDate { get; set; }

    public virtual ICollection<CustomerFavorite> CustomerFavorite { get; set; } = new List<CustomerFavorite>();

    public virtual ICollection<PostTaggedProduct> PostTaggedProduct { get; set; } = new List<PostTaggedProduct>();

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<ProductImg> ProductImg { get; set; } = new List<ProductImg>();

    public virtual ICollection<ProductSpecification> ProductSpecification { get; set; } = new List<ProductSpecification>();

    public virtual ICollection<SellerStatistic> SellerStatistic { get; set; } = new List<SellerStatistic>();

    public virtual Supplier Supplier { get; set; }
}