// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ProductReturn
{
    public int ReturnId { get; set; }

    public int OrderId { get; set; }

    public int UserId { get; set; }

    public string Reason { get; set; }

    public decimal RefundAmount { get; set; }

    public string Status { get; set; }

    public DateTimeOffset ReturnDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<ProductReturnDetail> ProductReturnDetail { get; set; } = new List<ProductReturnDetail>();

    public virtual User User { get; set; }
}