// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ProductImg
{
    public int ProductImgId { get; set; }

    public int ProductId { get; set; }

    public string ProductImgFile { get; set; }

    public virtual Product Product { get; set; }
}