// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class ProductReturnDetail
{
    public int ReturnDetailId { get; set; }

    public int ReturnId { get; set; }

    public int OrderDetailId { get; set; }

    public int Quantity { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual ProductReturn Return { get; set; }
}