// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class SellerStatistic
{
    public int SellerStatisticsId { get; set; }

    public int ProductId { get; set; }

    public int? AddCartCount { get; set; }

    public int? CheckoutCount { get; set; }

    public int? ViewCount { get; set; }

    public int? FavorCount { get; set; }

    public DateTimeOffset StatisticsDate { get; set; }

    public virtual Product Product { get; set; }
}