// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Shipper
{
    public int ShipperId { get; set; }

    public string ShipperName { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();
}