// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class Supplier
{
    public int SupplierId { get; set; }

    public string SupplierName { get; set; }

    public string ContactName { get; set; }

    public string ContactTitle { get; set; }

    public string ContactEmail { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();
}