// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset UpdatedAt { get; set; }

    public int UserType { get; set; }

    public int Status { get; set; }

    public bool? TwoFactorEnabled { get; set; }

    public string TwoFactorSecret { get; set; }

    public string CountryCode { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual ICollection<CommunityFavorite> CommunityFavorite { get; set; } = new List<CommunityFavorite>();

    public virtual ICollection<CommunityPost> CommunityPost { get; set; } = new List<CommunityPost>();

    public virtual ICollection<CustomerFavorite> CustomerFavorite { get; set; } = new List<CustomerFavorite>();

    public virtual ICollection<GroupCart> GroupCart { get; set; } = new List<GroupCart>();

    public virtual ICollection<GroupCustomerFavorite> GroupCustomerFavorite { get; set; } = new List<GroupCustomerFavorite>();

    public virtual ICollection<GroupOrder> GroupOrder { get; set; } = new List<GroupOrder>();

    public virtual ICollection<GroupPaymentMethod> GroupPaymentMethod { get; set; } = new List<GroupPaymentMethod>();

    public virtual ICollection<Order> Order { get; set; } = new List<Order>();

    public virtual ICollection<PaymentMethod> PaymentMethod { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<PostComment> PostComment { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLike { get; set; } = new List<PostLike>();

    public virtual ICollection<Review> Review { get; set; } = new List<Review>();

    public virtual ICollection<UserAddress> UserAddress { get; set; } = new List<UserAddress>();

    public virtual ICollection<UserFollow> UserFollowFollower { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserFollow> UserFollowFollowing { get; set; } = new List<UserFollow>();

    public virtual ICollection<UserOAuth> UserOAuth { get; set; } = new List<UserOAuth>();

    public virtual ICollection<UserProfile> UserProfile { get; set; } = new List<UserProfile>();
}