// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class UserAddress
{
    public int UserAddressId { get; set; }

    public int UserId { get; set; }

    public string RecipientName { get; set; }

    public string RecipientPhone { get; set; }

    public string PostalCode { get; set; }

    public string AddressDetail { get; set; }

    public bool? IsDefault { get; set; }

    public virtual User User { get; set; }
}