// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class UserFollow
{
    public int UserFollowId { get; set; }

    public int FollowerId { get; set; }

    public int FollowingId { get; set; }

    public DateTimeOffset FollowDate { get; set; }

    public virtual User Follower { get; set; }

    public virtual User Following { get; set; }
}