// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class UserRefreshToken
{
    public int UserRefreshTokenId { get; set; }

    public int UserId { get; set; }

    public string TokenHash { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset ExpiresAt { get; set; }

    public DateTimeOffset? RevokedAt { get; set; }

    public string ReplacedByTokenHash { get; set; }

    public virtual User User { get; set; }
}