// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class UserOAuth
{
    public int UserOAuthId { get; set; }

    public int UserId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public virtual User User { get; set; }
}