// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CLOthings_API.Models;

public partial class UserProfile
{
    public int UserProfileId { get; set; }

    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Avatar { get; set; }

    public string Gender { get; set; }

    public DateOnly? Birthday { get; set; }

    public string StyleTag { get; set; }

    public string Intro { get; set; }   

    public virtual User User { get; set; }
}